openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts App
  description: REST API documentation for the Contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html


servers:
  - url: http://localhost:3000/api
    description: Local development server
  - url: https://contacts-app-uz3k.onrender.com
    description: Production server

tags:
  - name: Contacts
    description: Operations related to managing user contacts (CRUD, favorites, photos)
  - name: Auth
    description: Authentication and authorization operations (login, logout, reset password)
  - name: Stories
    description: Operations related to managing travel stories (CRUD, images, categories)

paths:

  /users:
    get:
      $ref: '../swagger/paths/users/get.yaml'
  #   post:
  #     $ref: '../swagger/paths/users/post.yaml'
  # /users/{Id}:
  #   get:
  #     $ref: '../swagger/paths/users/{Id}/get.yaml'
  #   patch:
  #     $ref: '../swagger/paths/users/{Id}/patch.yaml'
  #   delete:
  #     $ref: '../swagger/paths/users/{Id}/delete.yaml'

  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/reset-pwd.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/send-reset-email.yaml'

  /stories:
    get:
      $ref: '../swagger/paths/stories/get.yaml'

  /stories/{storyId}:
    patch:
      $ref: '../swagger/paths/stories/{storyId}/patch.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
